/* $chaos: xemacs-script,v 1.5 2002/05/23 11:22:14 per Exp $ */
/* Abstract: Time module header file. */
/* Author: Per Lundberg <per@chaosdev.org> */

/* Copyright 2002 chaos development. */
/* Use freely under the terms listed in the file COPYING. */

#ifndef __TIME_H__
#define __TIME_H__

#include <storm/storm.h>
#include <log/log.h>

/* The IRQ generated by the RTC chip. */
#define RTC_IRQ                         8

/* The base address of the RTC controller. */
#define RTC_BASE                        0x70
#define RTC_COMMAND                     RTC_BASE
#define RTC_DATA                        (RTC_BASE + 1)
#define RTC_PORTS                       2

/* The RTC registers. */
#define RTC_REGISTER_SECOND             0x00
#define RTC_REGISTER_MINUTE             0x02
#define RTC_REGISTER_HOUR               0x04
#define RTC_REGISTER_DATE               0x07
#define RTC_REGISTER_MONTH              0x08
#define RTC_REGISTER_YEAR               0x09
#define RTC_REGISTER_A                  0x0A
#define RTC_REGISTER_B                  0x0B
#define RTC_REGISTER_C                  0x0C

#endif /* !__TIME_H__ */
