# $chaos$

# Abstract: storm G3 makefile
# Authors: Henrik Hallin <hal@chaosdev.org>
#          Per Lundberg <per@chaosdev.org>

# Copyright 2002 chaos development.

GENERIC_OBJECTS =
export GENERIC_OBJECTS

all:
	$(MAKE) -C ia32

clean::
	$(MAKE) -C ia32 clean

install:
	$(MAKE) -C ia32 install

include $(BUILD_ROOT)/storm.make
