# $chaos: makefile,v 1.2 2002/05/27 19:08:02 per Exp $

# Abstract: storm G3 makefile
# Authors: Per Lundberg <per@chaosdev.org>

# Copyright 2002 chaos development.

install:
	$(MAKE) -C storm install

include $(BUILD_ROOT)/storm.make
